// 001_fred_root_categories.cypher
//
// Purpose:
//   Create the initial FRED provider/category graph and import the
//   root FRED categories generated by MATLAB.
//
// Required generated input:
//   file:///fred_root_categories.csv
//
// Generated by:
//   src/fred_catalog_build.m
//
// Graph entities:
//   (:Provider {provider_id})
//   (:Category {provider_id, category_id})
//   (:Category)-[:CHILD_OF]->(:Category)

CREATE CONSTRAINT provider_id_unique IF NOT EXISTS
FOR (p:Provider)
REQUIRE p.provider_id IS UNIQUE;

CREATE CONSTRAINT category_key_unique IF NOT EXISTS
FOR (c:Category)
REQUIRE (c.provider_id, c.category_id) IS UNIQUE;

MERGE (provider:Provider {provider_id: "fred"})
SET provider.name = "Federal Reserve Economic Data",
    provider.short_name = "FRED",
    provider.api_base_url = "https://api.stlouisfed.org/fred/",
    provider.project = "Data_Retrival";

MERGE (root:Category {
    provider_id: "fred",
    category_id: "0"
})
SET root.name = "FRED Root",
    root.parent_id = "",
    root.is_root = true,
    root.catalog_source = "Project structural root";

LOAD CSV WITH HEADERS
FROM "file:///fred_root_categories.csv"
AS row

MATCH (root:Category {
    provider_id: row.provider_id,
    category_id: "0"
})

MERGE (category:Category {
    provider_id: row.provider_id,
    category_id: row.category_id
})

SET category.name = row.name,
    category.parent_id = row.parent_id,
    category.is_root = false,
    category.catalog_source = "FRED category/children",
    category.import_file = "fred_root_categories.csv"

MERGE (category)-[:CHILD_OF]->(root);

MATCH (root:Category {
    provider_id: "fred",
    category_id: "0"
})

OPTIONAL MATCH (category:Category {
    provider_id: "fred"
})-[:CHILD_OF]->(root)

RETURN root.name AS root_category,
       count(category) AS imported_root_categories;
