function audit = audit_fred_datalist_normalization(manifest)
%AUDIT_FRED_DATALIST_NORMALIZATION Validate metadata and normalized outputs.

arguments
    manifest (1,1) struct
end

requiredFields = [ ...
    "provider_id"
    "dataset_id"
    "raw_file_path"
    "raw_file_sha256"
];

for k = 1:numel(requiredFields)
    assert(isfield(manifest, requiredFields(k)), ...
        "Manifest is missing required field: %s", requiredFields(k));
end

assert(string(manifest.provider_id) == "fred", ...
    "This audit requires provider_id = 'fred'.");
assert(isfile(manifest.raw_file_path), ...
    "Registered raw ZIP does not exist: %s", manifest.raw_file_path);

root = currentProject().RootFolder;
shaPrefix = extractBefore(string(manifest.raw_file_sha256), 13);

stagingDir = fullfile( ...
    root, ...
    "data", "staging", "normalized", "fred", ...
    "fred_public_datalist_10578_fed_assets_" + shaPrefix);

assert(isfolder(stagingDir), ...
    "Staging directory does not exist: %s", stagingDir);

metadataPath = fullfile(stagingDir, "series_metadata.csv");
weeklyPath = fullfile(stagingDir, "normalized_weekly.csv");
wednesdayPath = fullfile( ...
    stagingDir, "normalized_weekly_ending_wednesday.csv");

assert(isfile(metadataPath), ...
    "Metadata catalog is missing: %s", metadataPath);
assert(isfile(weeklyPath), ...
    "Normalized weekly file is missing: %s", weeklyPath);
assert(isfile(wednesdayPath), ...
    "Normalized ending-Wednesday file is missing: %s", wednesdayPath);

metadata = readtable(metadataPath, "TextType", "string");

requiredMetadataColumns = [ ...
    "series_id"
    "frequency"
    "raw_archive_sha256"
    "dataset_id"
];

assert(all(ismember(requiredMetadataColumns, ...
    string(metadata.Properties.VariableNames))), ...
    "Metadata catalog is missing one or more required columns.");

assert(height(metadata) > 0, "Metadata catalog is empty.");
assert(all(strlength(metadata.series_id) > 0), ...
    "Metadata catalog contains empty series IDs.");
assert(numel(unique(metadata.series_id)) == height(metadata), ...
    "Metadata catalog contains duplicate series IDs.");
assert(all(metadata.dataset_id == string(manifest.dataset_id)), ...
    "Metadata dataset_id does not match registered manifest dataset_id.");
assert(all(metadata.raw_archive_sha256 == ...
    string(manifest.raw_file_sha256)), ...
    "Metadata SHA-256 does not match registered raw ZIP SHA-256.");

weeklySummary = summarize_normalized_member( ...
    weeklyPath, ...
    "weekly.csv", ...
    "Weekly", ...
    manifest);

wednesdaySummary = summarize_normalized_member( ...
    wednesdayPath, ...
    "weekly,_ending_wednesday.csv", ...
    "Weekly, Ending Wednesday", ...
    manifest);

normalizedSeriesIDs = unique([ ...
    weeklySummary.series_ids
    wednesdaySummary.series_ids]);

metadataSeriesIDs = unique(metadata.series_id);

missingMetadata = setdiff(normalizedSeriesIDs, metadataSeriesIDs);
orphanMetadata = setdiff(metadataSeriesIDs, normalizedSeriesIDs);

assert(isempty(missingMetadata), ...
    "Normalized series IDs missing from metadata: %s", ...
    strjoin(missingMetadata, ", "));

assert(isempty(orphanMetadata), ...
    "Metadata series IDs absent from normalized outputs: %s", ...
    strjoin(orphanMetadata, ", "));

weeklyMetadataIDs = unique(metadata.series_id( ...
    metadata.frequency == "Weekly"));

wednesdayMetadataIDs = unique(metadata.series_id( ...
    metadata.frequency == "Weekly, Ending Wednesday"));

weeklyFrequencyMismatch = setxor( ...
    weeklySummary.series_ids, weeklyMetadataIDs);

wednesdayFrequencyMismatch = setxor( ...
    wednesdaySummary.series_ids, wednesdayMetadataIDs);

assert(isempty(weeklyFrequencyMismatch), ...
    "Weekly member and metadata frequency assignment differ: %s", ...
    strjoin(weeklyFrequencyMismatch, ", "));

assert(isempty(wednesdayFrequencyMismatch), ...
    "Ending-Wednesday member and metadata frequency assignment differ: %s", ...
    strjoin(wednesdayFrequencyMismatch, ", "));

assert(numel(normalizedSeriesIDs) == height(metadata), ...
    "Normalized/metadata series-count mismatch: %d normalized, %d metadata.", ...
    numel(normalizedSeriesIDs), height(metadata));

auditTimeUTC = string(datetime( ...
    "now", ...
    TimeZone="UTC", ...
    Format="yyyy-MM-dd'T'HH:mm:ss'Z'"));

audit = struct( ...
    "provider_id", string(manifest.provider_id), ...
    "dataset_id", string(manifest.dataset_id), ...
    "raw_archive_sha256", string(manifest.raw_file_sha256), ...
    "staging_directory", string(stagingDir), ...
    "audit_at_utc", auditTimeUTC, ...
    "metadata_series_count", height(metadata), ...
    "weekly_series_count", numel(weeklySummary.series_ids), ...
    "weekly_row_count", weeklySummary.row_count, ...
    "weekly_nonmissing_value_count", weeklySummary.nonmissing_value_count, ...
    "ending_wednesday_series_count", numel(wednesdaySummary.series_ids), ...
    "ending_wednesday_row_count", wednesdaySummary.row_count, ...
    "ending_wednesday_nonmissing_value_count", ...
        wednesdaySummary.nonmissing_value_count, ...
    "normalized_union_series_count", numel(normalizedSeriesIDs), ...
    "status", "passed");

fprintf("Audit passed.\n");
fprintf("  Metadata base series: %d\n", audit.metadata_series_count);
fprintf("  Weekly base series: %d\n", audit.weekly_series_count);
fprintf("  Weekly normalized rows: %d\n", audit.weekly_row_count);
fprintf("  Ending-Wednesday base series: %d\n", ...
    audit.ending_wednesday_series_count);
fprintf("  Ending-Wednesday normalized rows: %d\n", ...
    audit.ending_wednesday_row_count);
fprintf("  Total unique base series: %d\n", ...
    audit.normalized_union_series_count);
end

function summary = summarize_normalized_member( ...
    normalizedPath, expectedSourceMember, expectedFrequency, manifest)

opts = detectImportOptions(normalizedPath, "TextType", "string");

requiredColumns = [ ...
    "provider_id"
    "dataset_id"
    "raw_archive_sha256"
    "source_member_path"
    "frequency_label"
    "series_id"
    "value"
    "is_missing"
];

assert(all(ismember(requiredColumns, string(opts.VariableNames))), ...
    "Normalized file is missing one or more required columns: %s", ...
    normalizedPath);

normalized = readtable(normalizedPath, opts);

assert(height(normalized) > 0, ...
    "Normalized file contains no rows: %s", normalizedPath);

assert(all(normalized.provider_id == string(manifest.provider_id)), ...
    "Provider mismatch in normalized file: %s", normalizedPath);

assert(all(normalized.dataset_id == string(manifest.dataset_id)), ...
    "Dataset ID mismatch in normalized file: %s", normalizedPath);

assert(all(normalized.raw_archive_sha256 == ...
    string(manifest.raw_file_sha256)), ...
    "SHA-256 mismatch in normalized file: %s", normalizedPath);

assert(all(normalized.source_member_path == expectedSourceMember), ...
    "Source-member mismatch in normalized file: %s", normalizedPath);

assert(all(normalized.frequency_label == expectedFrequency), ...
    "Frequency-label mismatch in normalized file: %s", normalizedPath);

assert(all(strlength(normalized.series_id) > 0), ...
    "Empty series ID found in normalized file: %s", normalizedPath);

summary = struct( ...
    "series_ids", unique(normalized.series_id), ...
    "row_count", height(normalized), ...
    "nonmissing_value_count", sum(~normalized.is_missing));
end
