function result = export_fred_category_crawl_neo4j_catalog(responsePattern)
%EXPORT_FRED_CATEGORY_CRAWL_NEO4J_CATALOG Export FRED category JSON to CSV.
%
% result = export_fred_category_crawl_neo4j_catalog(responsePattern)
%
% Reads existing category_*.json FRED API response files and writes Neo4j
% import CSVs. It does not call the FRED API or connect to Neo4j.

arguments
    responsePattern (1,1) string {mustBeNonempty}
end

responseFiles = dir(responsePattern);

assert(~isempty(responseFiles), ...
    "No FRED category response files match: %s", responsePattern);

responseDirectory = string(responseFiles(1).folder);

exportDirectory = fullfile( ...
    fileparts(fileparts(responseDirectory)), ...
    "neo4j_export");

assert(~isfolder(exportDirectory), ...
    "Refusing to overwrite existing export directory: %s", ...
    exportDirectory);

[ok, message] = mkdir(exportDirectory);

assert(ok, ...
    "Could not create Neo4j export directory: %s", message);

categories = table( ...
    strings(0, 1), ...
    strings(0, 1), ...
    strings(0, 1), ...
    strings(0, 1), ...
    VariableNames=[ ...
        "category_key"
        "category_id"
        "name"
        "parent_category_id"]);

for k = 1:numel(responseFiles)
    responsePath = fullfile(responseFiles(k).folder, responseFiles(k).name);

    response = jsondecode(fileread(responsePath));

    assert(isstruct(response), ...
        "JSON response is not an object: %s", responsePath);

    assert(isfield(response, "categories"), ...
        "FRED response lacks categories field: %s", responsePath);

    records = response.categories;

    if isempty(records)
        continue
    end

    if isstruct(records)
        records = num2cell(records(:));

    elseif iscell(records)
        assert(all(cellfun(@isstruct, records)), ...
            "categories contains a non-struct cell in: %s", responsePath);

        records = records(:);

    else
        error( ...
            "Unsupported categories payload class '%s' in: %s", ...
            class(records), responsePath);
    end

       for j = 1:numel(records)
        record = records(j);

        assert(isfield(record, "id"), ...
            "Category record lacks id: %s", responsePath);

        assert(isfield(record, "name"), ...
            "Category record lacks name: %s", responsePath);

        assert(isfield(record, "parent_id"), ...
            "Category record lacks parent_id: %s", responsePath);

        categoryID = string(record.id);
        parentCategoryID = string(record.parent_id);
        categoryName = string(record.name);

        categories = [categories; table( ...
            "fred:category:" + categoryID, ...
            categoryID, ...
            categoryName, ...
            parentCategoryID, ...
            VariableNames=categories.Properties.VariableNames)]; %#ok<AGROW>
    end
end

assert(~isempty(categories), ...
    "No category records were found in matching response files.");

[uniqueCategoryIDs, firstRows] = unique(categories.category_id, "stable");

categories = categories(firstRows, :);
categories = sortrows(categories, "category_id");

assert(height(categories) == numel(uniqueCategoryIDs), ...
    "Duplicate category IDs remain after de-duplication.");

categoryNodesPath = fullfile(exportDirectory, "fred_categories.csv");

writetable(categories, categoryNodesPath);

nonRoot = categories.parent_category_id ~= "0";

categoryEdges = table( ...
    categories.category_key(nonRoot), ...
    "fred:category:" + categories.parent_category_id(nonRoot), ...
    repmat("CHILD_OF", nnz(nonRoot), 1), ...
    VariableNames=[ ...
        "child_category_key"
        "parent_category_key"
        "relationship_type"]);

categoryEdgesPath = fullfile(exportDirectory, ...
    "fred_category_parent_relationships.csv");

writetable(categoryEdges, categoryEdgesPath);

exportManifest = struct( ...
    "provider_id", "fred", ...
    "source_response_pattern", responsePattern, ...
    "source_response_directory", responseDirectory, ...
    "response_file_count", numel(responseFiles), ...
    "category_node_count", height(categories), ...
    "root_category_child_count", nnz(~nonRoot), ...
    "parent_relationship_count", height(categoryEdges), ...
    "exported_at_utc", string(datetime( ...
        "now", ...
        TimeZone="UTC", ...
        Format="yyyy-MM-dd'T'HH:mm:ss'Z'")), ...
    "export_files", [ ...
        "fred_categories.csv"
        "fred_category_parent_relationships.csv"
        "export_manifest.json"]);

exportManifestPath = fullfile(exportDirectory, "export_manifest.json");

fileID = fopen(exportManifestPath, "w");

assert(fileID >= 0, ...
    "Could not open export manifest: %s", exportManifestPath);

cleanup = onCleanup(@() fclose(fileID));

fprintf(fileID, "%s", jsonencode(exportManifest, PrettyPrint=true));

fprintf("FRED category Neo4j export completed.\n");
fprintf("  Response files: %d\n", numel(responseFiles));
fprintf("  Category nodes: %d\n", height(categories));
fprintf("  Parent relationships: %d\n", height(categoryEdges));
fprintf("  Export directory: %s\n", exportDirectory);

result = struct( ...
    "response_file_count", numel(responseFiles), ...
    "category_node_count", height(categories), ...
    "parent_relationship_count", height(categoryEdges), ...
    "export_directory", string(exportDirectory), ...
    "category_nodes_path", string(categoryNodesPath), ...
    "category_relationships_path", string(categoryEdgesPath), ...
    "export_manifest_path", string(exportManifestPath));
end

