function result = export_fred_datalist_neo4j_catalog(manifest, audit)
%EXPORT_FRED_DATALIST_NEO4J_CATALOG Export audited FRED catalog CSVs.

arguments
    manifest (1,1) struct
    audit (1,1) struct
end

requiredManifestFields = [ ...
    "provider_id"
    "dataset_id"
    "source_url"
    "raw_file_path"
    "raw_file_sha256"
    "raw_file_bytes"
    "original_file_name"
    "raw_file_name"
    "registered_at_utc"
];

for k = 1:numel(requiredManifestFields)
    assert(isfield(manifest, requiredManifestFields(k)), ...
        "Manifest is missing required field: %s", ...
        requiredManifestFields(k));
end

requiredAuditFields = [ ...
    "status"
    "audit_at_utc"
    "metadata_series_count"
    "weekly_series_count"
    "weekly_row_count"
    "weekly_nonmissing_value_count"
    "ending_wednesday_series_count"
    "ending_wednesday_row_count"
    "ending_wednesday_nonmissing_value_count"
    "normalized_union_series_count"
];

for k = 1:numel(requiredAuditFields)
    assert(isfield(audit, requiredAuditFields(k)), ...
        "Audit is missing required field: %s", ...
        requiredAuditFields(k));
end

assert(string(manifest.provider_id) == "fred", ...
    "This exporter requires provider_id = 'fred'.");

assert(string(audit.status) == "passed", ...
    "Refusing Neo4j export because audit status is not 'passed'.");

assert(isfile(manifest.raw_file_path), ...
    "Registered raw ZIP does not exist: %s", manifest.raw_file_path);

root = currentProject().RootFolder;
shaPrefix = extractBefore(string(manifest.raw_file_sha256), 13);

stagingDir = fullfile( ...
    root, ...
    "data", "staging", "normalized", "fred", ...
    "fred_public_datalist_10578_fed_assets_" + shaPrefix);

assert(isfolder(stagingDir), ...
    "Expected staging directory does not exist: %s", stagingDir);

metadataPath = fullfile(stagingDir, "series_metadata.csv");

assert(isfile(metadataPath), ...
    "Expected series metadata CSV does not exist: %s", metadataPath);

metadata = readtable(metadataPath, "TextType", "string");

assert(height(metadata) == audit.metadata_series_count, ...
    "Metadata count differs from passed audit.");

assert(numel(unique(metadata.series_id)) == height(metadata), ...
    "Series metadata contains duplicate series IDs.");

exportDir = fullfile( ...
    root, ...
    "data", "catalog", "neo4j", "exports", ...
    string(manifest.dataset_id) + "_" + shaPrefix);

if isfolder(exportDir)
    error("Refusing to overwrite existing Neo4j export directory: %s", ...
        exportDir);
end

[ok, msg, msgID] = mkdir(exportDir);
assert(ok, "Could not create export directory: %s (%s)", msg, msgID);

providerNodes = table( ...
    string(manifest.provider_id), ...
    "FRED", ...
    "Federal Reserve Economic Data", ...
    "https://fred.stlouisfed.org", ...
    VariableNames=[ ...
        "provider_id"
        "display_name"
        "description"
        "homepage_url"]);

datasetNodes = table( ...
    string(manifest.dataset_id), ...
    string(manifest.provider_id), ...
    "10578", ...
    "banks weekly", ...
    string(manifest.source_url), ...
    "staged_audited", ...
    string(audit.status), ...
    string(audit.audit_at_utc), ...
    double(audit.metadata_series_count), ...
    double(audit.normalized_union_series_count), ...
    VariableNames=[ ...
        "dataset_id"
        "provider_id"
        "source_datalist_id"
        "title"
        "source_url"
        "ingestion_status"
        "audit_status"
        "audit_at_utc"
        "metadata_series_count"
        "normalized_series_count"]);

rawArtifactNodes = table( ...
    string(manifest.raw_file_sha256), ...
    string(manifest.dataset_id), ...
    double(manifest.raw_file_bytes), ...
    string(manifest.original_file_name), ...
    string(manifest.raw_file_name), ...
    string(manifest.raw_file_path), ...
    string(manifest.registered_at_utc), ...
    "immutable_raw", ...
    VariableNames=[ ...
        "sha256"
        "dataset_id"
        "bytes"
        "original_file_name"
        "raw_file_name"
        "raw_file_path"
        "registered_at_utc"
        "storage_class"]);

sourceMemberNodes = table( ...
    [string(manifest.dataset_id); string(manifest.dataset_id)], ...
    ["weekly.csv"; "weekly,_ending_wednesday.csv"], ...
    ["Weekly"; "Weekly, Ending Wednesday"], ...
    [117; 252], ...
    [13; 28], ...
    [double(audit.weekly_row_count); ...
     double(audit.ending_wednesday_row_count)], ...
    [double(audit.weekly_nonmissing_value_count); ...
     double(audit.ending_wednesday_nonmissing_value_count)], ...
    VariableNames=[ ...
        "dataset_id"
        "member_path"
        "frequency_label"
        "data_column_count"
        "base_series_count"
        "normalized_row_count"
        "nonmissing_value_count"]);

seriesNodes = table( ...
    "fred:" + metadata.series_id, ...
    metadata.series_id, ...
    metadata.dataset_id, ...
    metadata.source_datalist_id, ...
    metadata.title, ...
    metadata.source, ...
    metadata.release, ...
    metadata.units_level, ...
    metadata.frequency, ...
    metadata.seasonal_adjustment, ...
    metadata.real_time_start, ...
    metadata.period_end, ...
    metadata.notes, ...
    metadata.raw_archive_sha256, ...
    VariableNames=[ ...
        "catalog_key"
        "series_id"
        "dataset_id"
        "source_datalist_id"
        "title"
        "source"
        "release"
        "units_level"
        "frequency"
        "seasonal_adjustment"
        "real_time_start"
        "period_end"
        "notes"
        "raw_archive_sha256"]);

transformCodes = [ ...
    "LEVEL"
    "CCA"
    "CCH"
    "CH1"
    "CHG"
    "LOG"
    "PC1"
    "PCA"
    "PCH"];

nSeries = height(seriesNodes);
nTransforms = numel(transformCodes);
nVariants = nSeries * nTransforms;

variantSeriesID = repelem(seriesNodes.series_id, nTransforms, 1);
variantDatasetID = repelem(seriesNodes.dataset_id, nTransforms, 1);
variantFrequency = repelem(seriesNodes.frequency, nTransforms, 1);
variantTransform = repmat(transformCodes, nSeries, 1);

rawColumnName = variantSeriesID;

for k = 1:nVariants
    if variantTransform(k) ~= "LEVEL"
        rawColumnName(k) = variantSeriesID(k) + "_" + variantTransform(k);
    end
end

memberPath = strings(nVariants, 1);

isWeekly = variantFrequency == "Weekly";
isWednesday = variantFrequency == "Weekly, Ending Wednesday";

memberPath(isWeekly) = "weekly.csv";
memberPath(isWednesday) = "weekly,_ending_wednesday.csv";

assert(all(memberPath ~= ""), ...
    "At least one series has an unsupported or missing frequency.");

variantNodes = table( ...
    "fred:" + variantSeriesID + ":" + variantTransform, ...
    "fred:" + variantSeriesID, ...
    variantSeriesID, ...
    variantDatasetID, ...
    variantTransform, ...
    rawColumnName, ...
    memberPath, ...
    variantFrequency, ...
    VariableNames=[ ...
        "variant_key"
        "series_catalog_key"
        "series_id"
        "dataset_id"
        "transformation_code"
        "raw_column_name"
        "source_member_path"
        "frequency_label"]);

providersPath = fullfile(exportDir, "providers.csv");
datasetsPath = fullfile(exportDir, "datasets.csv");
rawArtifactsPath = fullfile(exportDir, "raw_artifacts.csv");
sourceMembersPath = fullfile(exportDir, "source_members.csv");
seriesPath = fullfile(exportDir, "series.csv");
variantsPath = fullfile(exportDir, "series_variants.csv");

writetable(providerNodes, providersPath);
writetable(datasetNodes, datasetsPath);
writetable(rawArtifactNodes, rawArtifactsPath);
writetable(sourceMemberNodes, sourceMembersPath);
writetable(seriesNodes, seriesPath);
writetable(variantNodes, variantsPath);

exportedAtUTC = string(datetime( ...
    "now", ...
    TimeZone="UTC", ...
    Format="yyyy-MM-dd'T'HH:mm:ss'Z'"));

exportFiles = [ ...
    "providers.csv"
    "datasets.csv"
    "raw_artifacts.csv"
    "source_members.csv"
    "series.csv"
    "series_variants.csv"
    "export_manifest.json"];

exportManifest = struct( ...
    "provider_id", string(manifest.provider_id), ...
    "dataset_id", string(manifest.dataset_id), ...
    "raw_archive_sha256", string(manifest.raw_file_sha256), ...
    "audit_status", string(audit.status), ...
    "audit_at_utc", string(audit.audit_at_utc), ...
    "exported_at_utc", exportedAtUTC, ...
    "provider_node_count", height(providerNodes), ...
    "dataset_node_count", height(datasetNodes), ...
    "raw_artifact_node_count", height(rawArtifactNodes), ...
    "source_member_node_count", height(sourceMemberNodes), ...
    "series_node_count", height(seriesNodes), ...
    "series_variant_node_count", height(variantNodes), ...
    "export_files", exportFiles);

exportManifestPath = fullfile(exportDir, "export_manifest.json");

fid = fopen(exportManifestPath, "w");
assert(fid >= 0, ...
    "Could not open export manifest for writing: %s", exportManifestPath);

cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s", jsonencode(exportManifest, PrettyPrint=true));

fprintf("Neo4j catalog export completed.\n");
fprintf("  Export directory: %s\n", exportDir);
fprintf("  Provider nodes: %d\n", height(providerNodes));
fprintf("  Dataset nodes: %d\n", height(datasetNodes));
fprintf("  Raw artifact nodes: %d\n", height(rawArtifactNodes));
fprintf("  Source member nodes: %d\n", height(sourceMemberNodes));
fprintf("  Series nodes: %d\n", height(seriesNodes));
fprintf("  Series variant nodes: %d\n", height(variantNodes));

result = struct( ...
    "export_directory", string(exportDir), ...
    "providers_path", string(providersPath), ...
    "datasets_path", string(datasetsPath), ...
    "raw_artifacts_path", string(rawArtifactsPath), ...
    "source_members_path", string(sourceMembersPath), ...
    "series_path", string(seriesPath), ...
    "series_variants_path", string(variantsPath), ...
    "export_manifest_path", string(exportManifestPath), ...
    "series_count", height(seriesNodes), ...
    "series_variant_count", height(variantNodes));
end
