function crawl = fred_category_tree_crawl()
%FRED_CATEGORY_TREE_CRAWL Resumable breadth-first crawl of FRED categories.
%
% crawl = fred_category_tree_crawl()
%
% Uses fred_category_children.m and fred_api_request.m.
% The function checkpoints after every successful parent-category request.
% Re-running the function resumes the active crawl.

root = currentProject().RootFolder;

crawlDirectory = fullfile( ...
    root, "data", "catalog", "fred", "crawls", "active");

responseDirectory = fullfile(crawlDirectory, "responses");

if ~isfolder(responseDirectory)
    mkdir(responseDirectory);
end

checkpointFile = fullfile(crawlDirectory, "checkpoint.mat");
manifestFile = fullfile(crawlDirectory, "crawl_manifest.json");
categoriesFile = fullfile(crawlDirectory, "all_categories.csv");
visitedFile = fullfile(crawlDirectory, "visited_parent_ids.csv");
failuresFile = fullfile(crawlDirectory, "failures.csv");

requestDelaySeconds = 1.0;
maximumRetries = 5;
maximumBackoffSeconds = 60;

if isfile(checkpointFile)
    load(checkpointFile, ...
        "queue", ...
        "visitedParentIDs", ...
        "allCategories", ...
        "failures", ...
        "startedAt");

    fprintf("Resuming crawl.\n");
    fprintf("Queued parent categories: %d\n", numel(queue));
    fprintf("Already visited parents: %d\n", numel(visitedParentIDs));

else
    queue = 0;

    visitedParentIDs = zeros(0,1);

    allCategories = table( ...
        zeros(0,1), ...
        strings(0,1), ...
        zeros(0,1), ...
        VariableNames = ["CategoryID", "Name", "ParentID"]);

    failures = table( ...
        zeros(0,1), ...
        strings(0,1), ...
        strings(0,1), ...
        zeros(0,1), ...
        VariableNames = ["ParentID", "TimestampUTC", "Message", "Attempts"]);

    startedAt = datetime("now", TimeZone="UTC");

    manifest = struct( ...
        "provider", "fred", ...
        "crawl_type", "full_category_tree", ...
        "started_at_utc", string(startedAt), ...
        "status", "running", ...
        "request_delay_seconds", requestDelaySeconds, ...
        "maximum_retries", maximumRetries, ...
        "root_category_id", 0);

    write_text_file(manifestFile, jsonencode(manifest, PrettyPrint=true));

    fprintf("Starting new crawl from FRED root category 0.\n");
end

while ~isempty(queue)
    parentID = queue(1);
    queue(1) = [];

    if ismember(parentID, visitedParentIDs)
        continue
    end

    fprintf( ...
        "[%s] Parent %d | queue: %d | visited: %d\n", ...
        string(datetime("now", TimeZone="UTC"), ...
        "yyyy-MM-dd HH:mm:ss"), ...
        parentID, ...
        numel(queue), ...
        numel(visitedParentIDs));

    success = false;
    attempt = 0;
    lastMessage = "";

    while ~success && attempt < maximumRetries
        attempt = attempt + 1;

        try
            [children, rawResponse] = fred_category_children(parentID);

            responseFile = fullfile( ...
                responseDirectory, ...
                "category_" + string(parentID) + ".json");

            rawResponseText = jsonencode(rawResponse, PrettyPrint=true);

            write_text_file(responseFile, rawResponseText);

            if ~isempty(children)
                allCategories = [allCategories; children];
                allCategories = unique(allCategories, "rows", "stable");

                childIDs = children.CategoryID(:);
                unseenChildren = childIDs(~ismember( ...
                    childIDs, [visitedParentIDs; queue]));

                queue = [queue; unseenChildren];
            end

            visitedParentIDs = [visitedParentIDs; parentID];
            visitedParentIDs = unique(visitedParentIDs, "stable");

            success = true;

        catch exception
            lastMessage = string(exception.message);

            if attempt < maximumRetries
                waitSeconds = min( ...
                    maximumBackoffSeconds, ...
                    2^(attempt - 1) * requestDelaySeconds);

                fprintf( ...
                    "  Attempt %d/%d failed: %s\n", ...
                    attempt, maximumRetries, lastMessage);

                fprintf( ...
                    "  Waiting %.1f seconds before retry.\n", ...
                    waitSeconds);

                pause(waitSeconds);
            end
        end
    end

    if ~success
        failures = [failures; { ...
            parentID, ...
            string(datetime("now", TimeZone="UTC")), ...
            lastMessage, ...
            attempt}];

        visitedParentIDs = [visitedParentIDs; parentID];
        visitedParentIDs = unique(visitedParentIDs, "stable");

        fprintf( ...
            "  Parent %d failed after %d attempts. Recorded and skipped.\n", ...
            parentID, attempt);
    end

    writetable(allCategories, categoriesFile);
    writetable(table(visitedParentIDs, ...
        VariableNames="ParentID"), visitedFile);
    writetable(failures, failuresFile);

    save(checkpointFile, ...
        "queue", ...
        "visitedParentIDs", ...
        "allCategories", ...
        "failures", ...
        "startedAt", ...
        "requestDelaySeconds", ...
        "maximumRetries", ...
        "maximumBackoffSeconds");

    if ~isempty(queue)
        pause(requestDelaySeconds);
    end
end

manifest = struct( ...
    "provider", "fred", ...
    "crawl_type", "full_category_tree", ...
    "started_at_utc", string(startedAt), ...
    "completed_at_utc", string(datetime("now", TimeZone="UTC")), ...
    "status", "complete", ...
    "request_delay_seconds", requestDelaySeconds, ...
    "maximum_retries", maximumRetries, ...
    "categories_discovered", height(allCategories), ...
    "parent_categories_visited", numel(visitedParentIDs), ...
    "failed_parent_categories", height(failures), ...
    "root_category_id", 0);

write_text_file(manifestFile, jsonencode(manifest, PrettyPrint=true));

crawl = struct( ...
    directory, string(crawlDirectory), ...
    categories, allCategories, ...
    visited_parent_ids, visitedParentIDs, ...
    failures, failures, ...
    completed, true);

fprintf("\nCrawl complete.\n");
fprintf("Categories discovered: %d\n", height(allCategories));
fprintf("Parents visited: %d\n", numel(visitedParentIDs));
fprintf("Failed parents: %d\n", height(failures));
fprintf("Catalog CSV: %s\n", categoriesFile);

end

function write_text_file(filename, text)
fileID = fopen(filename, "w");

if fileID == -1
    error("fred:FileWriteFailed", ...
        "Could not open file for writing: %s", filename);
end

cleanup = onCleanup(@() fclose(fileID));
fprintf(fileID, "%s", text);
end