function descriptor = fred_datalist_descriptor(manifest)
%FRED_DATALIST_DESCRIPTOR Derive FRED data-list paths from an intake manifest.
%
% This function is read-only. It does not modify the manifest, raw files,
% staging artifacts, catalog exports, or Neo4j.

arguments
    manifest (1,1) struct
end

requiredFields = [ ...
    "provider_id"
    "dataset_id"
    "source_url"
    "raw_file_path"
    "raw_file_sha256"
    "raw_file_bytes"
    "ingestion_status"];

for k = 1:numel(requiredFields)
    assert(isfield(manifest, requiredFields(k)), ...
        "Manifest is missing required field: %s", requiredFields(k));
end

assert(string(manifest.provider_id) == "fred", ...
    "fred_datalist_descriptor requires provider_id = 'fred'.");

assert(isfile(manifest.raw_file_path), ...
    "Registered raw file does not exist: %s", manifest.raw_file_path);

sourceURL = string(manifest.source_url);

assert(~ismissing(sourceURL) && strlength(strtrim(sourceURL)) > 0, ...
    "A nonempty FRED public data-list source_url is required.");

tokens = regexp(sourceURL, ...
    '/public/datalist/([0-9]+)(?:[/?#].*)?$', ...
    'tokens', 'once');

assert(~isempty(tokens), ...
    "source_url is not a recognized FRED public data-list URL: %s", ...
    sourceURL);

dataListID = string(tokens{1});
sha256 = lower(string(manifest.raw_file_sha256));

assert(strlength(sha256) == 64 && ...
    ~isempty(regexp(sha256, '^[0-9a-f]{64}$', 'once')), ...
    "Manifest raw_file_sha256 is not a 64-character lowercase hex SHA-256.");

shaPrefix = extractBefore(sha256, 13);
datasetID = string(manifest.dataset_id);

root = currentProject().RootFolder;

canonicalKey = datasetID + "_" + shaPrefix;

stagingParent = fullfile(root, "data", "staging", "normalized", "fred");
exportParent = fullfile(root, "data", "catalog", "neo4j", "exports");

canonicalStagingDirectory = fullfile(stagingParent, canonicalKey);
canonicalExportDirectory = fullfile(exportParent, canonicalKey);

stagingDirectory = discover_matching_directory( ...
    stagingParent, shaPrefix, canonicalStagingDirectory, "staging");

exportDirectory = discover_matching_directory( ...
    exportParent, shaPrefix, canonicalExportDirectory, "Neo4j export");

descriptor = struct( ...
    "provider_id", "fred", ...
    "dataset_id", datasetID, ...
    "source_url", sourceURL, ...
    "source_datalist_id", dataListID, ...
    "raw_file_path", string(manifest.raw_file_path), ...
    "raw_file_bytes", double(manifest.raw_file_bytes), ...
    "raw_file_sha256", sha256, ...
    "sha256_prefix", shaPrefix, ...
    "staging_key", canonicalKey, ...
    "staging_directory", string(stagingDirectory), ...
    "staging_directory_is_canonical", ...
        string(stagingDirectory) == string(canonicalStagingDirectory), ...
    "neo4j_export_key", canonicalKey, ...
    "neo4j_export_directory", string(exportDirectory), ...
    "neo4j_export_directory_is_canonical", ...
        string(exportDirectory) == string(canonicalExportDirectory), ...
    "descriptor_created_at_utc", string(datetime( ...
        "now", ...
        TimeZone="UTC", ...
        Format="yyyy-MM-dd'T'HH:mm:ss'Z'")));
end

function directory = discover_matching_directory( ...
    parentDirectory, shaPrefix, canonicalDirectory, label)

if isfolder(canonicalDirectory)
    directory = canonicalDirectory;
    return
end

assert(isfolder(parentDirectory), ...
    "%s parent directory does not exist: %s", label, parentDirectory);

entries = dir(parentDirectory);
entries = entries([entries.isdir]);

names = string({entries.name});
names = names(names ~= "." & names ~= "..");

matches = names(endsWith(names, shaPrefix));

assert(numel(matches) <= 1, ...
    ["Ambiguous %s directories ending with SHA prefix %s: %s. " + ...
     "Refusing to guess."], ...
    label, shaPrefix, strjoin(matches, ", "));

if isempty(matches)
    directory = canonicalDirectory;
else
    directory = fullfile(parentDirectory, matches);
end
end
